### PR TITLE
Add credit to domain host

### PR DESCRIPTION
**Pull request by spectrapulse**

### CODE REVIEW

**Comment by Huntears** [comment]
uwu

**Comment by Huntears** [comment]
OwO

**Comment by Huntears** [comment]
i like this one

**Comment by spectrapulse** [comment]
Same

**Comment by Huntears** [comment]
yas

**Comment by Huntears** [comment]
that gonna be some god damn good branch tho

**Comment by Huntears** [comment]
uwu^2

**Pull request merged**
